---
title: "Installing ctags and GNU global"
author: 
  - "Mark Padgham"
date: "`r Sys.Date()`"
output: 
    html_document:
        toc: true
        toc_float: true
        number_sections: false
        theme: flatly
vignette: >
  %\VignetteIndexEntry{Installation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = TRUE,
  message = TRUE,
  width = 120,
  comment = "#>",
  fig.retina = 2,
  fig.path = "README-"
)
```

The `pkgstats` package requires installation of the two system libraries,
[`universal-ctags`](https://ctags.io) and [GNU
`global`](https://www.gnu.org/software/global/). These libraries are very small
and generally relatively quick to install, even when compiled from source.
Installation is nevertheless not straightforward because
[`universal-ctags`](https://ctags.io) is a fork of another project, and is not
officially supported on all systems. This vignette describes how to install
these necessary libraries on Linux, MacOS, and Windows operating systems.

## Linux

The easiest way to install these libraries on any Linux system is to compile
them both from source, for which the procedure is identical for all Linux
operating systems. First compile and install `ctags` with the following lines:

```{bash, eval = FALSE}
git clone https://github.com/universal-ctags/ctags.git
cd ctags
./autogen.sh
./configure --prefix=/usr
make
sudo make install
```

[GNU `global`](https://www.gnu.org/software/global/) can generally be installed
from most Linux package managers, for example through `apt-get install global`
for Ubuntu, or `pacman -S global` for Archlinux.

## MaxOS

```{bash, eval = FALSE}
brew install --HEAD universal-ctags/universal-ctags/universal-ctags
brew install global
```


## Windows via [chocalatey](https://chocolatey.org)

The easiest way to install the required libraries on Windows is via [chocalatey](https://chocolatey.org):

```{bash, eval = FALSE}
choco install universal-ctags global
```

## Windows via [`msys2`](https://www.msys2.org/)

Installation on Windows without using [chocalatey](https://chocolatey.org)
requires [`msys2`](https://www.msys2.org/) which is installated as part of
[Rtools40](https://cran.r-project.org/bin/windows/Rtools/). The following lines
will download, compile, and install [`universal-ctags`](https://ctags.io).

```{bash, eval = FALSE}
git clone https://github.com/universal-ctags/ctags.git
cd ctags
./autogen.sh
./configure --prefix=/usr
make V=1
make install
```

[GNU `global`](https://www.gnu.org/software/global/) can then be downloaded as
a pre-compiled binary from
[http://adoxa.altervista.org/global/](http://adoxa.altervista.org/global/)
(generally as the latest Win32 version - there is no 64-bit version). The
downloaded file then just needs to be unzipped and installed.
