// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// loc.cpp
writable::integers cpp_loc(const strings flist, const strings cmt_open, const strings cmt_close, const strings cmt);
extern "C" SEXP _pkgstats_cpp_loc(SEXP flist, SEXP cmt_open, SEXP cmt_close, SEXP cmt) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_loc(cpp11::as_cpp<cpp11::decay_t<const strings>>(flist), cpp11::as_cpp<cpp11::decay_t<const strings>>(cmt_open), cpp11::as_cpp<cpp11::decay_t<const strings>>(cmt_close), cpp11::as_cpp<cpp11::decay_t<const strings>>(cmt)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_pkgstats_cpp_loc", (DL_FUNC) &_pkgstats_cpp_loc, 4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_pkgstats(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
