# Generated by cpp11: do not edit by hand

cpp_white_space <- function(flist) {
  .Call(`_pkgstats_cpp_white_space`, flist)
}

cpp_parse_rd <- function(flist) {
  .Call(`_pkgstats_cpp_parse_rd`, flist)
}
