# Generated by cpp11: do not edit by hand

cpp_loc <- function(flist, cmt_open, cmt_close, cmt) {
  .Call(`_pkgstats_cpp_loc`, flist, cmt_open, cmt_close, cmt)
}

cpp_parse_rd <- function(flist) {
  .Call(`_pkgstats_cpp_parse_rd`, flist)
}
